version: '3'

volumes:
  es-vt-data:
    driver: local

networks:
  elastic:
    driver: bridge

services:
  es_tileserv:
    image: igarashijin/es_tileserv:latest
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    environment: 
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports:
      - "8080:8080"
    depends_on: 
      - elasticsearch
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      #- discovery.seed_hosts=es02
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-vt-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

